// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * ConfigType 配置文件类型枚举
 */
export enum ConfigType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    INI = 0,
    $JSON = 1,
    PROPERTIES = 2,
    YAML = 3,
};

/**
 * ProcessType 定义进程类型
 */
export enum ProcessType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ConPty = 0,
    Ordinary = 1,
};
