// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllAppConfig() {
  return window['go']['src']['App']['GetAllAppConfig']();
}

export function GetAppConfigByKey(arg1) {
  return window['go']['src']['App']['GetAppConfigByKey'](arg1);
}

export function GetMcAllConfig() {
  return window['go']['src']['App']['GetMcAllConfig']();
}

export function GetMcConfigByKey(arg1) {
  return window['go']['src']['App']['GetMcConfigByKey'](arg1);
}

export function GetMcServerStatus() {
  return window['go']['src']['App']['GetMcServerStatus']();
}

export function GetOsState() {
  return window['go']['src']['App']['GetOsState']();
}

export function OpenMcServerDirectoryDialog() {
  return window['go']['src']['App']['OpenMcServerDirectoryDialog']();
}

export function OpenProxyServerDirectoryDialog() {
  return window['go']['src']['App']['OpenProxyServerDirectoryDialog']();
}

export function SendCommandToMcServer(arg1) {
  return window['go']['src']['App']['SendCommandToMcServer'](arg1);
}

export function SendMessageToLLOneBot(arg1) {
  return window['go']['src']['App']['SendMessageToLLOneBot'](arg1);
}

export function StartMcServer() {
  return window['go']['src']['App']['StartMcServer']();
}

export function StopMcServer() {
  return window['go']['src']['App']['StopMcServer']();
}

export function UpDataAppConfig(arg1, arg2) {
  return window['go']['src']['App']['UpDataAppConfig'](arg1, arg2);
}

export function UpDataMcConfig(arg1, arg2) {
  return window['go']['src']['App']['UpDataMcConfig'](arg1, arg2);
}
