// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function GetAllAppConfig():Promise<entity.AppConfig>;

export function GetAppConfigByKey(arg1:string):Promise<string>;

export function GetMcAllConfig():Promise<entity.McServerConfig>;

export function GetMcConfigByKey(arg1:string):Promise<string>;

export function GetMcServerStatus():Promise<entity.McServerState>;

export function GetOsState():Promise<entity.OsState>;

export function OpenMcServerDirectoryDialog():Promise<string>;

export function OpenProxyServerDirectoryDialog():Promise<string>;

export function SendCommandToMcServer(arg1:string):Promise<void>;

export function SendMessageToLLOneBot(arg1:string):Promise<void>;

export function StartMcServer():Promise<string>;

export function StopMcServer():Promise<void>;

export function UpDataAppConfig(arg1:string,arg2:any):Promise<void>;

export function UpDataMcConfig(arg1:string,arg2:string):Promise<void>;
