// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v_manager$0 from "../../Common/Manager/models.js";

export function DelValueOfKey(uuid: string, key: string): Promise<string | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2286143964, uuid, key) as any;
    return $resultPromise;
}

export function GetAllValue(uuid: string): Promise<[any, string | null]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3652559366, uuid) as any;
    return $resultPromise;
}

export function GetValueOfKey(uuid: string, key: string, section: string): Promise<[string | null, string | null]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1170376773, uuid, key, section) as any;
    return $resultPromise;
}

export function NewConfigManager(managerType: v_manager$0.ConfigType, filePath: string, abs: boolean): Promise<[string | null, string | null]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4229052301, managerType, filePath, abs) as any;
    return $resultPromise;
}

export function SetValueOfKey(uuid: string, key: string, value: any, section: string): Promise<string | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(548618313, uuid, key, value, section) as any;
    return $resultPromise;
}
