// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ConfigIpc from "./configipc.js";
import * as LoggerIpc from "./loggeripc.js";
import * as PluginIpc from "./pluginipc.js";
import * as ProcessIpc from "./processipc.js";
import * as SystemDialogIpc from "./systemdialogipc.js";
import * as UtilsIpc from "./utilsipc.js";
export {
    ConfigIpc,
    LoggerIpc,
    PluginIpc,
    ProcessIpc,
    SystemDialogIpc,
    UtilsIpc
};
