// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function CloseLogger(uuid: string): Promise<string | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1438327604, uuid) as any;
    return $resultPromise;
}

export function LogDebug(uuid: string, logLine: string): Promise<string | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(701590537, uuid, logLine) as any;
    return $resultPromise;
}

export function LogError(uuid: string, logLine: string): Promise<string | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1180539720, uuid, logLine) as any;
    return $resultPromise;
}

export function LogInfo(uuid: string, logLine: string): Promise<string | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3242441182, uuid, logLine) as any;
    return $resultPromise;
}

export function LogWarn(uuid: string, logLine: string): Promise<string | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2569647710, uuid, logLine) as any;
    return $resultPromise;
}

export function NewLogger(logDir: string, logFileName: string, date: boolean): Promise<[string | null, string | null]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1281003270, logDir, logFileName, date) as any;
    return $resultPromise;
}
