// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entity$0 from "../../Common/Entity/models.js";

export function GetPluginList(): Promise<entity$0.Plugin[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3878304786) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function LoadPlugins(): Promise<string | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2738386341) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = entity$0.Plugin.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType1);
