// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entity$0 from "../../Common/Entity/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v_manager$0 from "../../Common/Manager/models.js";

/**
 * GetProcessStatus 获取指定ID进程的状态。
 * 返回 (状态指针, 错误信息字符串)
 */
export function GetProcessStatus(id: number): Promise<[entity$0.ProcessState | null, string | null]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1036456930, id) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function NewProcess(processType: v_manager$0.ProcessType, abs: boolean, relPath: string, ...args: string[]): Promise<number> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2444685578, processType, abs, relPath, args) as any;
    return $resultPromise;
}

/**
 * SendCommand 向指定ID的进程发送命令。
 */
export function SendCommand(id: number, command: string): Promise<string | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3627603176, id, command) as any;
    return $resultPromise;
}

/**
 * Start 启动指定ID的进程。
 * 返回一个 string 类型的错误信息，如果成功则为空字符串。
 */
export function Start(id: number): Promise<string | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2315626635, id) as any;
    return $resultPromise;
}

/**
 * Stop 停止指定ID的进程。
 */
export function Stop(id: number): Promise<string | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2009285497, id) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = entity$0.ProcessState.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
