// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function AuthDirectory(path: string, filesList: string[][]): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3947075498, path, filesList) as any;
    return $resultPromise;
}

export function OpenDirectoryDialog(title: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3255972832, title) as any;
    return $resultPromise;
}

export function OpenFileDialog(title: string, displayName: string, pattern: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1691650151, title, displayName, pattern) as any;
    return $resultPromise;
}
