// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entity$0 from "../../Common/Entity/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v_utils$0 from "../../Common/Utils/models.js";

export function GetBeServerStatus(host: string, port: number): Promise<entity$0.BedrockMcServerStatus | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3138424375, host, port) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetSystemState(): Promise<entity$0.SystemState | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3782633799) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function HttpRequest(options: v_utils$0.HttpRequestOptions): Promise<[string | null, string | null]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4158981214, options) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = entity$0.BedrockMcServerStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = entity$0.SystemState.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
